development:
  adapter: mysql2
  database: id_count_sandbox_development
  username: root
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: id_count_sandbox_test
  username: root
  password:
  encoding: utf8
